#!/usr/bin/env python3
"""
Generates a high-fidelity land mask for Athena's globe from Natural Earth data.

    python3 Scripts/make-coastline.py            # 1° resolution (default)
    python3 Scripts/make-coastline.py --deg 0.75 # finer, bigger file

Downloads ne_110m_land.geojson (public domain), rasterises it to a lat/lon
bitmask, and writes Athena/News/LandMaskData.swift — a compact base64 bit
array the app decodes at launch. No runtime network, no third-party deps.
"""
import argparse
import base64
import json
import os
import sys
import urllib.request

URL = ("https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
       "master/geojson/ne_110m_land.geojson")
OUT = os.path.join(os.path.dirname(__file__), "..", "Athena", "News", "LandMaskData.swift")


def polygons_from_geojson(gj):
    """Flattens the FeatureCollection into a list of outer rings."""
    rings = []
    for feature in gj.get("features", []):
        geom = feature.get("geometry") or {}
        kind, coords = geom.get("type"), geom.get("coordinates") or []
        if kind == "Polygon":
            rings.append(coords[0])
        elif kind == "MultiPolygon":
            for poly in coords:
                rings.append(poly[0])
    return rings


def bbox(ring):
    xs = [p[0] for p in ring]
    ys = [p[1] for p in ring]
    return min(xs), min(ys), max(xs), max(ys)


def point_in_ring(x, y, ring):
    """Standard ray-casting test."""
    inside = False
    n = len(ring)
    j = n - 1
    for i in range(n):
        xi, yi = ring[i][0], ring[i][1]
        xj, yj = ring[j][0], ring[j][1]
        if (yi > y) != (yj > y):
            slope = (xj - xi) / (yj - yi) if (yj - yi) else 0
            if x < xi + slope * (y - yi):
                inside = not inside
        j = i
    return inside


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--deg", type=float, default=1.0,
                    help="grid resolution in degrees (default 1.0)")
    args = ap.parse_args()
    step = args.deg

    print(f"→ downloading Natural Earth land polygons…")
    with urllib.request.urlopen(URL, timeout=90) as response:
        gj = json.loads(response.read().decode("utf-8"))

    rings = polygons_from_geojson(gj)
    print(f"  {len(rings)} rings")

    boxes = [bbox(r) for r in rings]

    cols = int(round(360 / step))
    rows = int(round(180 / step))
    print(f"→ rasterising {cols}×{rows} grid ({cols * rows:,} cells)…")

    bits = bytearray((cols * rows + 7) // 8)
    land_count = 0

    for row in range(rows):
        lat = 90 - (row + 0.5) * step
        for col in range(cols):
            lon = -180 + (col + 0.5) * step
            hit = False
            for ring, (minx, miny, maxx, maxy) in zip(rings, boxes):
                if lon < minx or lon > maxx or lat < miny or lat > maxy:
                    continue
                if point_in_ring(lon, lat, ring):
                    hit = True
                    break
            if hit:
                index = row * cols + col
                bits[index >> 3] |= (1 << (index & 7))
                land_count += 1
        if row % 20 == 0:
            print(f"  row {row}/{rows}", end="\r", flush=True)

    coverage = land_count / (cols * rows) * 100
    print(f"\n  {land_count:,} land cells ({coverage:.1f}% — Earth is ~29% land)")

    encoded = base64.b64encode(bytes(bits)).decode("ascii")
    chunks = [encoded[i:i + 100] for i in range(0, len(encoded), 100)]
    literal = "\n".join(f'    "{c}" +' for c in chunks[:-1]) + f'\n    "{chunks[-1]}"'

    swift = f'''// Generated by Scripts/make-coastline.py — do not edit by hand.
// Source: Natural Earth ne_110m_land (public domain).
// {cols}x{rows} grid at {step}° resolution, 1 bit per cell, row-major from 90°N.

import Foundation

enum LandMaskData {{
    static let columns = {cols}
    static let rows = {rows}
    static let degrees = {step}

    /// Base64 bit array; bit set = land.
    static let packed =
{literal}

    /// Decoded once on first use.
    static let bits: [UInt8] = Data(base64Encoded: packed).map {{ [UInt8]($0) }} ?? []

    static func isLand(row: Int, col: Int) -> Bool {{
        guard row >= 0, row < rows, !bits.isEmpty else {{ return false }}
        let c = ((col % columns) + columns) % columns
        let index = row * columns + c
        let byte = index >> 3
        guard byte < bits.count else {{ return false }}
        return bits[byte] & (1 << UInt8(index & 7)) != 0
    }}
}}
'''

    path = os.path.abspath(OUT)
    with open(path, "w") as f:
        f.write(swift)
    size_kb = len(swift) / 1024
    print(f"✓ wrote {path} ({size_kb:.0f} KB)")
    print("\nNext:  xcodegen && open Athena.xcodeproj")


if __name__ == "__main__":
    sys.exit(main())
